security:
  oauth2:
    resource:
      jwt:
        key-value: secret
    client:
      client-id: gateway
      client-secret: gateway
      access-token-uri: http://sc-security-uaa/oauth/token
      user-authorization-uri: http://sc-security-uaa/oauth/authorize
spring:
  http:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  redis:
    database: 9
    host: 127.0.0.1
#servlet:
#  multipart:
#    enabled: true #是否启用http上传处理
#    max-request-size: 100MB #最大请求文件的大小
#    max-file-size: 20MB #设置单个文件最大长度
#    file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
zuul:
  routes:
    uaa:
      path: /uaa/**
      serviceId: sc-security-uaa
    web:
      path: /web/**
      serviceId: sc-web
      sensitiveHeaders:
    webauth:
      path: /webauth/**
      serviceId: sc-web-auth
      sensitiveHeaders:
    job:
      path: /job/**
      serviceId: sc-job
      sensitiveHeaders:
    project:
      path: /project/**
      serviceId: sc-project
      sensitiveHeaders:
    pc:
      path: /pc/**
      serviceId: sc-xzsd-pc
      sensitiveHeaders:
    app:
      path: /app/**
      serviceId: sc-xzsd-app
      sensitiveHeaders:
  add-proxy-headers: true
  add-host-header: true
  retryable: false
request:
  limit:
    enabled: true
    max-connections: 2000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 20000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1